# here we use the data description
COLUMNS: 
fixed activity: float64
volatile activity: float64
citric activity: float64
residual sugar: float64
chlorides: float64
free sulfur dioxide: float64
total sulfur dioxide: float64
density: float64
pH: float64
sulphate: float64
alcohol: float64
quality: int64

TARGET_COLUMN:
name: quality